package com.semseytech.rtsdevicesuitepro.tools.logs

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import androidx.core.content.FileProvider
import java.io.File
import java.text.SimpleDateFormat
import java.util.*

object LogExporter {

    fun generateLogMarkdown(context: Context): File {
        val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
        val fileName = "RTS_Log_$timestamp.md"
        val logFile = File(context.cacheDir, fileName)

        val logcatContent = try {
            Runtime.getRuntime().exec("logcat -d").inputStream.bufferedReader().readText()
        } catch (e: Exception) {
            "Error capturing logcat: ${e.message}"
        }

        val mdContent = StringBuilder().apply {
            append("# RTS Device Suite Pro - System Log\n\n")
            append("## Device Information\n")
            append("- **Date:** ${Date()}\n")
            append("- **Model:** ${Build.MODEL}\n")
            append("- **Manufacturer:** ${Build.MANUFACTURER}\n")
            append("- **Android Version:** ${Build.VERSION.RELEASE} (API ${Build.VERSION.SDK_INT})\n")
            append("- **App Version:** 1.0\n\n")
            
            append("## Debug Data\n")
            append("```kotlin\n")
            append("// Relevant device state\n")
            append("val isLowRamDevice = ${Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT_WATCH}\n")
            append("val board = \"${Build.BOARD}\"\n")
            append("```\n\n")

            append("## System Logs (Logcat)\n")
            append("> This section contains the most recent system events and error traces.\n\n")
            append("```bash\n")
            append(logcatContent.takeLast(100000)) // Increased buffer
            append("\n```\n")
            
            append("\n---\n")
            append("*End of Log - Generated by RTS Device Suite Pro Security Module*")
        }.toString()

        logFile.writeText(mdContent)
        return logFile
    }

    fun shareLog(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/markdown"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Export Log"))
    }

    fun emailDeveloper(context: Context, file: File) {
        val uri = FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "message/rfc822"
            putExtra(Intent.EXTRA_EMAIL, arrayOf("semseytechnologies@proton.me"))
            putExtra(Intent.EXTRA_SUBJECT, "RTS Device Suite Pro Bug Report")
            putExtra(Intent.EXTRA_TEXT, "Please describe the issue you encountered:\n\n")
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Email Developer"))
    }
}
